### ISSUE TITLE
Unused js

### ISSUE THREAD

**Issue by MyNameTony1000** [dpmango/gulp-starter-pack#49]
Hello, tell me, did you set up the removal of unused js code in this webpack using google-closure-compiler or another tool?
(Здравствуйте, скажите, настраивали ли вы удаление неиспользуемого кода js в данном webpack при помощи google-closure-compiler или другого инструмента?)

**Comment by dpmango** [comment]
Hello. Currently there are no plans to add this feature, but it would be nice to have if you provide PR 
Webpack config is used in `/gulp/tasks/javascript.js`

Нет, но можете добавить конфиг вебпака и создать PR
