### ISSUE TITLE
Bootstrap 4 

### ISSUE THREAD

**Issue by kirillz** [dpmango/gulp-starter-pack#5]
Большое спасибо за сборку, очень впечатлила реализация. У меня вопрос а как использовать bootstrap в ней, и планируется ли внедрить его использование?

**Comment by dpmango** [comment]
Спасибо за добрые слова.

Внедрядь не планируется, подключить можно как и любую другую билиотеку
1 - установка зависимостей
`$ yarn add bootstrap`
`$ yarn add popper.js`

2 - поключение js в vendor.js
`import 'popper.js';`
`import 'bootstrap';`

3 - подключение css в app.sass
@import "bootstrap/scss/bootstrap";


https://getbootstrap.com/docs/4.0/getting-started/webpack/

**Comment by kirillz** [comment]
Благодарю!
